# .travis.yml
language: node_js

node_js:
  - 4.4
  - 4.6

matrix:
    allow_failures:

before_install:
  - node --version
  - npm -v
  - npm install -g grunt-cli bower

before_script:
  - npm run setup

script:
  - grunt travis

after_script:
