# Using trusty because the Travis Addon for SonarQube.com requires Java 8
dist: trusty
sudo: required

language: node_js

node_js:
    - 8.12
    - 10.0

matrix:
    allow_failures:

before_install:
    - node -v
    - npm -v

install:
    - npm run setup

before_script:

script:
    - npm run test
    - npm run release
    - npm run sonar

after_script:

cache:
    directories:
        - $HOME/.npm
        - $HOME/.sonar/cache
        - $HOME/.sonar/native-sonar-scanner
