# .travis.yml
language: node_js

node_js:
  - 4.4
  - 4.6

matrix:
    allow_failures:

before_install:
  - rvm install 2.2.2
  - node --version
  - npm -v

install:
  - npm install -g grunt-cli bower
  - npm run setup

before_script:

script:
  - grunt travis

after_script:
