# .travis.yml
language: node_js

node_js:
    - 8.12
    - 10.0

matrix:
    ? allow_failures

before_install:
    - node -v
    - npm -v

install:
    - npm run setup

? before_script

script:
    - npm run test
    - npm run release

? after_script
