const GET_DEMO1_ENDPOINT1_PART1 = "GET_SAMPLE_ENDPOINT_START";
const GET_DEMO1_ENDPOINT1_PART1_SUCCESS = "GET_DEMO1_ENDPOINT1_PART1_SUCCESS";
const GET_DEMO1_ENDPOINT1_PART1_FAILURE = "GET_DEMO1_ENDPOINT1_PART1_FAILURE";

const GET_DEMO2_ENDPOINT2_PART1 = "GET_DEMO2_ENDPOINT2_PART1";
const GET_DEMO2_ENDPOINT2_PART1_SUCCESS = "GET_DEMO2_ENDPOINT2_PART1_SUCCESS";
const GET_DEMO2_ENDPOINT2_PART1_FAILURE = "GET_DEMO2_ENDPOINT2_PART1_FAILURE";

const GET_DEMO2_ENDPOINT3_PART2 = "GET_DEMO2_ENDPOINT3_PART2";
const GET_DEMO2_ENDPOINT3_PART2_SUCCESS = "GET_DEMO2_ENDPOINT3_PART2_SUCCESS";
const GET_DEMO2_ENDPOINT3_PART2_FAILURE = "GET_DEMO2_ENDPOINT3_PART2_FAILURE";

const ARRAY_SORTING_SUCCESS = "ARRAY_SORTING_SUCCESS";
const ARRAY_SORTING_FAILURE = "ARRAY_SORTING_FAILURE";

const APPLICATION_ERROR = "APPLICATION_ERROR";

export default {
    GET_DEMO1_ENDPOINT1_PART1,
    GET_DEMO1_ENDPOINT1_PART1_SUCCESS,
    GET_DEMO1_ENDPOINT1_PART1_FAILURE,
    GET_DEMO2_ENDPOINT2_PART1,
    GET_DEMO2_ENDPOINT2_PART1_SUCCESS,
    GET_DEMO2_ENDPOINT2_PART1_FAILURE,
    GET_DEMO2_ENDPOINT3_PART2,
    GET_DEMO2_ENDPOINT3_PART2_SUCCESS,
    GET_DEMO2_ENDPOINT3_PART2_FAILURE,
    ARRAY_SORTING_SUCCESS,
    ARRAY_SORTING_FAILURE,
    APPLICATION_ERROR
};
